---
- name: Installing Jenkins on Ubuntu 22.04.
  when: ansible_distribution|lower == 'ubuntu' or ansible_os_family|lower == "debian"
  block:
    - name: Install depends.
      apt:
        name: "{{ ubuntu_java }}"
        state: present
    - name: Add an Apt siging key.
      get_url:
        url: "{{ apt_key }}"
        dest: "{{ key_path }}"
        force: true
    - name: Add Jenkins repo.
      apt_repository:
        repo: "{{ apt_repo }}"
        state: present
        filename: "{{ jenkins_package }}"
        update_cache: true
    - name: Install Jenkins package.
      apt:
        name: "{{ jenkins_package }}"
        state: present
    - name: Start and enable Jenkins service.
      service:
        name: "{{ jenkins_service }}"
        state: started
        enabled: true
    - name: Allow 8080/tcp port.
      ufw:
        port: "{{ jenkins_port }}"
        proto: 'tcp'
        rule: allow
        comment: Allow jenkins port
      ignore_errors: true

    - shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: cat_output
    - debug:
        msg: "initialAdminPassword for {{ inventory_hostname }}={{ cat_output.stdout }}"
    - name: Jenkins url.
      debug:
        msg: "jenkins url for {{ inventory_hostname }}=http://{{ ansible_default_ipv4.address }}:8080/"
...